/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc.seng301.wordleapp.lab5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertTrue(true);
    }
}
